session = ".session/donna"
default_section_kind = "donna.lib.text"
default_primary_section_id = "primary"
cache_lifetime = 1.0
workflow_dirs = ["./workflows", "./.session/donna"]

[journal]
cmd = ["./bin/taskwarior.sh", "log", "+journal", "+donna", "kind:event", "{message}"]
