session = ".session/donna"
default_section_kind = "donna.lib.text"
default_primary_section_id = "primary"
cache_lifetime = 1.0

[[file_filters]]
mode = "include"
pattern = "@/.session/donna/**/*.donna.md"

[[file_filters]]
mode = "include"
pattern = "@/.agents/**/*.donna.md"

[[file_filters]]
mode = "ignore"
pattern = ".*/**"

[[file_filters]]
mode = "include"
pattern = "**/*.donna.md"

[[file_filters]]
mode = "ignore"
pattern = "**"

[journal]
cmd = ["./bin/taskwarior.sh", "log", "+journal", "+donna", "kind:event", "{message}"]
