version = 1

session_dir = ".session/donna"
workflow_dirs = ["./workflows", "./.session/donna"]

[defaults]
tail_section_kind = "donna.lib.text"
primary_section_kind = "donna.lib.workflow"
primary_section_id = "primary"

[journal]
cmd = ["./bin/taskwarior.sh", "log", "+journal", "+donna", "kind:event", "{message}"]
