* TODO Possible workflows
** bootstrap.bootstrap_all.
** bootstrap.donna.create_project
** bootstrap.donna.craete_specifications
** bootstrap.python.create_grooming_workflow
** bootstrap.python.create_project
** morphologica_analysis — workflow for explicit morphological analysis
** simple_task — workflow for simple tasks to not bother with complex story workflows
** Spec-based workflow (like in OpenSpec?)
** Example worflow with iterative factorial calculation
** Example workflow with recursive factorial calculation
** Example of simplified groom (without run_script)
** Example of complex groom (with run_script)
** changy.summarize_changes
* TODO possible specifications
** how to prepare python package with artifacts for donna
** changy.cli
* TODO README.md notes
** `No API keys required.` as a feature
** `save tokens by taking work from your agent to your code`
** compare to https://github.com/Fission-AI/OpenSpec
*** fsms instead of plain texts
*** "better" Markdown
** you can deliver instructions and operations for your package with your package
** every error is accompanied with the ways to fix it
** goals:
*** maximum determinism
*** maximum introspection
*** maximum quality
*** LLMs must do only the work they can do better than code
*** not a goal: optimizing tokens (however, we do this when we can)
*** not a goal: optimizing speed (however, we do this when we can)
** How Donna help agents to do their work better
*** Validation of artifacts
*** Every error is accompanied with the explanation and list of ways to fix it
*** Do algorithmic operations without need for LLMs to think about them
*** Controls meta flow of work, so agent should not think about it
** Since the donna is developed with donna, Donna's `.donna` directory is a great example of how to structure donna workspaces and how to work with it in general.
** this is also an experiment on agent-friendly cli tools
** known problems
*** lack of reporting — when a long chain of automated operations is performed, there is no convenient report/logging of what donna doing
*** agent tools (like codes) does not properly report what is happening
**** action requests as a verbose approach vs run_script as a silent approach
** You can distribute your specs as a separate package or within your own lib and you don't need dependency on donna.
** list of python packages that support donna
*** changy
*** brigid
*** feeds fun
** I don't beliew in manual orchestrators, in the future, agents will be capable of orchestrating their work => donna is developed as a helpfull tool, not as a full-fledged orchestrator.
* TODO Specification improvements:
** do we need to explicitly reference `session.specification.work_scope.md` if its name has already specified in donna.specifications.planning?
** {{ edit(specification) }} directive?
** {{ run(workflow) }} directive?
* TODO Workflows polishing
** introduce donna:planing:* namespace
** Improve planing instuction to explictitly polish list of items (goals, etc.) base on other items forward and backward.
** Declare explicit refining loop
** Add mini workflows to polish each kind of records?
** meta_work_loop.md contains a lot of repetitive commands to read specifications. We should optimize them somehow.
*** Approach 1: move them to the head section text
*** Approach 2: move them to the head section config
*** Approach 3: keep them, but add some meta info on analysis phase that donna can use.
** tune wording of workflows (what to write before goto)
** Planing loop improvement: before initial planing and on each loop try to found uncertain parts of tasks and ask developer to clarify them. Like in deep research.
** completed session keeps work_scope.md and work_scope_execution.md artifacts, we must add cleanup on the first step of planing.
** on initialization donna should create some default workflows based on the project configs (grooming, for example)
* TODO Massive spellcheck
* TODO Donna-agents integration
** Install donna as a skill
** Install donna as a tool
** slash commands for donna
** installing donna cli via online instruction for agents
** specify usage modes somewhere:
*** easy mode — one of possible skills to use
*** hard mode — forse agent to work via donna
* TODO Workflows notes
** we need fully automatic workflow, we also need to be able to run subflows manually for better control
*** => multiple workfows
*** => operation to run a specific workflow
** each decomposition artifact/statement must be coupled with verification statement
** hypothesis generation as a separate workflow/artifact
** risk-driven approach:
*** a dedicated “risk register” artifact and stage gates based on uncertainty reduction: prototypes, experiments, or targeted tests are first-class deliverables.
*** https://cse.msu.edu/~cse435/Homework/HW3/boehm.pdf
*** `risk` can be coupled with `decission`
*** "have we reduced uncertainty enough to commit?" as a force for planning
** use nested directory structure to organize small artifacts, use patterns to extract them
*** theoretically, we can keep an artifact per requirement, they will just look like `session:planning:requirements:*`
** How to regulate complexity of workflows, depending on the task scope?
*** introduce an additional step/workflow to high-level analysis of the task scope and select appropriate workflow complexity
** How to name the group of workflows/artifacts that will incapulate the whole logic for donna?
** `collect-analyze-synthesize->apply` as a separate workflow to work on small tasks? This workflow may take an artifact with the task description as input and produces the report artifact as output. Or just update the original artifact with the report.
** Plan and exectute separation
*** planing -> prepare plan of work
*** execute one step of work -> analyze -> update plan if required
*** execute next step of work -> analyze -> update plan if required
*** …
** log of work?
** spec collection in the project: world: work on sessions most likely should update it?
** we should strive to implement small workflows which become building blocks for more complex workflows.
** "work-to-do.md" as an intermediate artifact between planning and execution?
*** may just collect an unsorted list of tasks to do
